name: scale_monk_example
description: Demonstrates how to use the scale_monk plugin.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scale_monk:
    path: ../

dev_dependencies:


flutter:
  uses-material-design: true