# include: package:lint/analysis_options.yaml
include: package:lint/analysis_options_package.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_setters_without_getters: false
